#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TMP_FILE=$(mktemp)
SCRIPT_NAME="IbyC-installer"
DB_iHAKLAB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
DB_IVAM3="https://raw.githubusercontent.com/ivam3/ivam3.github.io/master/master/installer/"

wget $DB_iHAKLAB/libexec/colors -O $TMP_FILE -q
source $TMP_FILE

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[w]:─➤ You need to be a common user$W\n"
	exit
done
#until [ -e $HOME/$SCRIPT_NAME ]; do
#	printf "$R\n[w]:─➤ $SCRIPT_NAME file have to be in Home directory$W\n"
#	exit
#done
#until ping -q -c1 -W 1 8.8.8.8 > /dev/null 2>&1 ; do
#	printf "$R\n[w]:─➤ Please connect to internet$W\n"
#	exit
#done

CC() {
	rm $PREFIX/tmp/tmp.* 2>/dev/null
	if [ -e $HOME/$TOOL ]
	then
		rm $HOME/$TOOL 2>/dev/null
	fi
}
ctrl_c() {
	CC
	printf "$Y\n[!]:─➤$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
	exit
}

Usage(){ wget $DB_IVAM3/usage -O $TMP_FILE -q 1>&2; chmod +x $TMP_FILE; exec $TMP_FILE; exit 1; }

Listools() {
	wget $DB_IVAM3/IbyC-list -O $TMP_FILE -q
}

Instatool() {
	wget $DB_IVAM3/tools/$TOOL -O $HOME/$TOOL -q
	chmod 711 $HOME/$TOOL
	bash $HOME/$TOOL
	rm $HOME/$TOOL
}

echo $(clear)
        printf "$C"
        echo "           -{ IbyC-installer } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"

if [ -z $1 ]
then
	Usage
	CC
fi

while getopts ":hlif" ARGS ; do
	case ${ARGS} in
		h)
			Usage
			CC
			;;
		l)
			MODULE=${OPTARG}
			Listools
			printf "$Goke\n      [IbyC]$W Tools Availables$Goke [IbyC]$W\n\n"
			cat -n $TMP_FILE
			CC
			;;
		i)
			if [ -z $2 ]
			then
				printf "$Goke\n[usage]:─➤$W IbyC-installer -i <name-of-tool>\n"
				CC
				exit
			else
				Listools
				TOOL=$(cat $TMP_FILE | grep -oE $2)
				if [ "$TOOL" = "$2" ]
				then
					Instatool
				else
					printf "$R\n[w]:─➤ The tool$W $2$R is not available\n"
					exit
				fi
			fi
			CC
			;;
		f)
			if [ "$2" = module ] 
			then
				wget $DB_iHAKLAB/bin/IbyC-fixer -O $PREFIX/bin/IbyC-fixer -q
				$(which IbyC-fixer) 
			elif [ "$2" = bigdecimal ]
			then
				wget $DB_iHAKLAB/.set/fix-tools/IbyC-fixbigdecimal -O $TMP_FILE -q
				exec $TMP_FILE
			else
				Usage
			fi
			CC
			;;
		*)
			printf "$R\n[w]:─➤ Invalid argument$W\n"
			CC
			exit
			;;
	esac
done
shift $((OPTIND-1))
CC
#		@Ivam3
