#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TMP_FILE=$PREFIX/tmp/tmp	#$(mktemp)
SCRIPT_NAME="IbyC-installer"
DB_iHAKLAB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
DB_IVAM3="https://raw.githubusercontent.com/ivam3/ivam3.github.io/master/master/installer/"

command -v ruby >/dev/null || apt install ruby -y >/dev/null 2>&1                                        command -v lolcat >/dev/null || gem install lolcat >/dev/null 2>&1
source $TMP_FILE.colors

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[w]:─➤ You need to be a common user$W\n"
	exit
done

CC() {
	rm $PREFIX/tmp/tmp.* 2>/dev/null
	if [ -e $HOME/$TOOL ]
	then
		rm $HOME/$TOOL 2>/dev/null
	fi
	}
ctrl_c(){ CC;printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}

Perm() { chmod 711 $TMP_FILE.* ;}

Usage(){ wget -q $DB_IVAM3/usage -O $TMP_FILE.usage 1>&2; chmod +x $TMP_FILE.usage; exec $TMP_FILE.usage; exit 1; }

Listools() {
	wget -q $DB_IVAM3/IbyC-list -O $TMP_FILE.list
	Perm
	}

Instatool() {
	wget -q $DB_IVAM3/tools/$TOOL -O $HOME/$TOOL
	chmod 711 $HOME/$TOOL
	bash $HOME/$TOOL
	rm $HOME/$TOOL
	}
Banner(){ printf " ___ _            ____   _           _        _ _\n|_ _| |__  _   _ / ___| (_)_ __  ___| |_ __ _| | | ___ _ __\n | || '_ \| | | | |     | | '_ \/ __| __/ _\` | | |/ _ \ '__|\n | || |_) | |_| | |___  | | | | \__ \ || (_| | | |  __/ |\n|___|_.__/ \__, |\____| |_|_| |_|___/\__\__,_|_|_|\___|_|\n           |___/Termux installer tools by @Ivam3byCinderella\n";}
Banner|lolcat

if [ -z $1 ]
then
	Usage
	CC
fi

while getopts ":hlif" ARGS ; do
	case ${ARGS} in
		h)
			Usage
			CC
			;;
		l)
			MODULE=${OPTARG}
			Listools
			printf "$Goke\n      [IbyC]$W Tools Availables$Goke [IbyC]$W\n\n"
			cat -n $TMP_FILE.list
			CC
			;;
		i)
			if [ -z $2 ]
			then
				printf "$Goke\n[usage]:─➤$W IbyC-installer -i <name-of-tool>\n"
				CC
				exit
			else
				Listools
				TOOL=$(cat $TMP_FILE.list | grep -oE $2)
				if [ "$TOOL" = "$2" ]
				then
					Instatool
				else
					printf "$R\n[w]:─➤ The tool$W $2$R is not available\n"
					exit
				fi
			fi
			CC
			;;
		f)
			wget $DB_iHAKLAB/bin/IbyC-fixer -O $PREFIX/bin/IbyC-fixer -q
			chmod +x $PREFIX/bin/IbyC-fixer
			$(which IbyC-fixer)
			CC
			;;
		*)
			printf "$R\n[w]:─➤ Invalid argument$W\n"
			CC
			exit
			;;
	esac
done
shift $((OPTIND-1))
CC
#		@Ivam3
