#!/data/data/com.termux/files/usr/bin/bash
#Created on Jan/2019
IFS=$'\n\t'
trap ctrl_c 2
#VAR
	R='\033[1;31m'
        G='\033[1;32m'
        Goke='\033[92m'
        Glig=='\e[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
function ctrl_c() {
                echo
                printf "$Y\n\n[!]$R O-ops!!$W Join to my Telegram bot >>$R t.me/Ivam3_Bot$W\n\n"
		sleep 2
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
while ! ping -q -c 1 -W 1 8.8.8.8 > /dev/null; do
        printf "$R[w]-> ERROR 404 | Please connect to some Network$W\n"
        exit
done
until [ -e ~/ivam3-Haklab ]; do
        printf "$R[w]-> ivam3-Haklab file need be in home directory$W\n"
	exit
done
for i in -----------------------@ IVAM3------------------@ IVAM3-HACKING----------@ IVAM3-HACKING-LABORATORY; do
echo $(clear)
printf "$C"
	echo "#-----THANKS TO MY MASTER CINDERELLA-----#"
        echo "#                                        #"
        echo "#             People don't die           #"
        echo "#    If they still live in the hearts    #"
        echo "#           of their loved ones          #"
        echo "#       We love her ... We miss her      #"
        echo "#                                        #"
        echo "#-------------------RIP------------------#"
	echo
        printf "$G STARTING TO INSTALL . . . .$W$i"
        printf "\n\n"
        sleep 1
done
git clone https://github.com/ivam3/i-Haklab.git $HOME/i-Haklab
cd ~/i-Haklab
chmod 711 -R *
bash setup
#                                               @Ivam3
