#!$PREFIX/bin/bash

pkg install util-linux
clear
setterm -foreground cyan
	  echo "              -{ (Ru)by  (G)em  (i)ssue (R)esolved RuGiR } "
          echo "                  -{ SO > Android - Only for Termux } "
          echo "                            -{ Coded by } "
setterm -foreground green
          echo "                   ==============================";
          echo "                   .___                  _______";
          echo "                   |   |__ ______   ___  \_____ \ ";
          echo "                   |  \ \/ /\__ \ /   \    (__ <,";
          echo "                   |   |\   / __ \| Y Y \ \      \ ";
          echo "                   |___| \_/ (____|__|_| /______ /";
          echo "                                 \/    \/      \/ ";
          echo "                   ====== By ___ Cinderella ======";
          echo
setterm -foreground cyan
          echo "                         [---] Join me on [---]"
          echo "             [-] www.youtube.com/c/ivam3bycinderella [-]"
	  echo "                           [-] t.me/ivam3 [-]"
          sleep 3

#Required v.4.16.16
	echo "
	"
	echo "             =================================================="
	echo "CINDERELLA : What is the version of your Metasploit-Framework ?"
	echo "             =================================================="
	echo
	echo "			     1) 4.16.16"
	echo "			     2) 4.16.4 or earlier "
	echo
	read -p "IbyC = " IbyC
	case $IbyC in
		1)

#Drop to trash
	clear
setterm -foreground magenta
	echo "
	"
	echo "		   ========================================="
	echo "		   CINDERELLA : I will eliminate the garbage"
	echo "		   ========================================="
	echo
setterm -foreground white
	sleep 3
apt remove -y git ruby ruby-dev make clang autoconf curl wget ncurses-utils libsqlite-dev postgresql-dev libpcap-dev libffi-dev libxslt-dev pkg-config

apt autoremove -y

#Re-installing repositories
	echo "
	"
setterm -foreground magenta
	echo "============================================="
	echo "CINDERELLA : Let me work in your repositories"
	echo "============================================="
	echo
	sleep 3
setterm -foreground white
apt -y install git ruby ruby-dev make clang autoconf curl wget ncurses-utils libsqlite-dev postgresql-dev libpcap-dev libffi-dev libxslt-dev pkg-config


#Adding updated gems at Gemfile.local
	echo "                                                                                                        "
setterm -foreground magenta
	echo "========================================="
	echo "CINDERELLA : Let's go fo fix those issues"
	echo "========================================="
	echo
	sleep 3
	setterm -foreground white
gem install bundler
gem install nokogiri -- --using-system-libraries
bundle config build.nokogiri -- using-system-libraries
echo "$PREFIX/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/nokogiri-1.8.0" >> Gemfile.local
bundle install --gemfile Gemfile.local
rm Gemfile.local
bundle install --full-index
bundle update nokogiri
ruby msfconsole -q
	
;;
	2)
		sleep 2
		if [ -e ./$PREFIX/bin/termux-open ]; then
		echo "Press enter para ser redireccionado al tutorial de instalacion o Ctrl+C para salir"
		read enter
		termux-open https://youtu.be/XcKHa-v4vH4
		else
		echo "CINDERELLA : Up's sorry but this script just work with msf-v.4.16.16"
		echo
		echo "Paste on your browser the link > https://youtu.be/XcKHa-v4vH4 and come to see my tutorial"
			exit
	fi
		;;
esac
