#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="sqlmap"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){
	printf "$Y\n\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
	exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
#CHECK ROOT
if [ -x /system/xbin/su ] || [ -x /su/bin/su ] || [ -x /sbin/su ]; then
        ROOT="YES"
fi
echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

setPath(){
	if [ -L $HOME/storage/external-1 ]; then
		SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
		if [ ! -z $SDCARD ]; then
			DIR=$SDCARD
		else
			DIR=$HOME
		fi
	else
		DIR=$HOME
	fi
	printf "$Y\n[IbyC]:->$W Set the directory where $SCRIPT_NAME will be install$Y\n[default]:->$W $DIR\n"
	read -p "[R]:-> " ANSW
	DIR="${ANSW:-${DIR}}"
}

#::::::::INSTALLATION:::::::::#
Termux(){
        for i in unstable-repo sqlmap; do
                PKG=$(pkg list-all|grep -o $i)
                if [ ! -z "$PKG" ]
                then
                        printf "$G\n[+]─➤$W Installing the repository $i $W\n"
                        yes|pkg install $i >/dev/null 2>&1
                else
                        printf "$R\n[w]─➤$W The repository $i is not candidate$W\n"
                        sleep 1
                fi
        done
}
Python(){
        yes|pkg install python python2 git
        for i in python python2 ; do
                $i -m pip --no-color install --upgrade pip -q
                $i -m pip --no-color install sqlmap -q
        done
}
Github(){
	setPath
        if [ -d $DIR/$TOOL ]
	then
		rm -rf $DIR/$TOOL
        fi
        git clone https://github.com/sqlmapproject/$TOOL $DIR/$TOOL
        chmod 711 -R $DIR/$TOOL
}

printf "$C#::::::::::::::::::::::::::::::::::::#$Y\n[!?]->$W Choose a type of installation$G\n[01]->$W Termux repositories$G\n[02]->$W Github$G\n[03]->$W Python-pip modules\n"
while read -p "[R]-> " ANSW && [ -z $ANSW ]; do
        continue
done
yes|pkg update && pkg upgrade
case $ANSW in
        01|1)
                Termux
                ;;
        02|2)
                Github
                ;;
        03|3)
                Python
                ;;
        *)
                ctrl_c
                exit
                ;;
esac

#ENDING SCRIPT
if [ -d $DIR/$TOOL ]; then
	endPath=$DIR/$TOOL
elif [ -e $PREFIX/bin/$TOOL ]; then
	endPath=$PREFIX/bin/$TOOL
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi

printf "$G\n[DIR TOOL]:->$W $endPath"
printf "$G\n[RUN IT]:->$W $TOOL or python $TOOL.py\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"

#                                               @Ivam3
