#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="sudo"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

#INSTALLATION
if [ ! -d $HOME/.suroot ]; then
        mkdir $HOME/.suroot
        touch $HOME/.suroot/.bashrc
fi
if [ "$ROOT" = "true" ]; then
        #set colored=true to turn on colored error messages
        #set colored=false to turn off colored error messages
        colored=true
        #red=1 green=2 yellow=3
        color() {
                if [ $colored == "true" ]; then
                        echo "$(tput setaf $1)${*:2}$(tput sgr0)"
                else
                        echo "${*:2}"
                fi
        }
        SYSBIN=/system/bin
        SYSXBIN=/system/xbin
        BB=$SYSXBIN/busybox
        PRE=/data/data/com.termux/files
        ROOT_HOME=$PRE/home/.suroot
        BINPRE=$PRE/usr/bin
        LDLP="export LD_LIBRARY_PATH=$PRE/usr/lib"
        CMDLINE="PATH=$PATH:$SYSXBIN:$SYSBIN;$LDLP;HOME=$ROOT_HOME;cd $PWD"

        if [ -x $SYSXBIN/su ]; then
                SU=$SYSXBIN/su
        elif [ -x /su/bin/su ]; then
                SU=/su/bin/su
        elif [ -x /sbin/su ]; then
                SU=/sbin/su
        fi
        if [ ! -d $ROOT_HOME ]; then
                if [ -x $BB ] && [ $($BB --list | grep -w mount) == "mount" ]; then
                        MOUNTEX="$BB mount"
                elif [ -x $SYSBIN/mount ]; then
                        MOUNTEX="$SYSBIN/mount"
                fi
                MOUNT_RW="$MOUNTEX -o rw,remount,rw /system"
                MOUNT_RO="$MOUNTEX -o ro,remount,ro /system"
                $SU -c "$MOUNT_RW"
                $SU -c "mkdir $ROOT_HOME"
                $SU -c "chmod 700 $ROOT_HOME"
                BASHRC="'PS1=\"# \"\nexport TERM=$TERM\n$LDLP\nexport PATH=$PATH:$SYSXBIN:$SYSBIN'"
                $SU -c "echo -e $BASHRC > $ROOT_HOME/.bashrc"
                $SU -c "chmod 700 $ROOT_HOME/.bashrc"
                $SU -c "$MOUNT_RO"
        fi
        # Reset echo
        stty sane
        if [ -e $PREFIX/bin/applets/sudo ]; then
                rm $PREFIX/bin/applets/sudo
        fi
        wget https://raw.githubusercontent.com/ivam3/ivam3.github.io/master/master/mediafire/sudo -O $PREFIX/bin/sudo -q
        chmod +x $PREFIX/bin/sudo
        sudo echo "HOME=/data/data/com.termux/files/home/storage/external-1/roothome" >> ~/.suroot/.bashrc
else
        printf "$R[W]:-> DEVICE NOT ROOTED$W\n\n"
	exit
fi

#ENDING SCRIPT
if [ -e $PREFIX/bin/$TOOL ]; then
	printf "$G\n[DIR TOOL]:->$W $PREFIX/bin/$TOOL"
	printf "$G\n[RUN IT]:->$W sudo su\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
