#!/data/data/com.termux/files/usr/bin/bash
#Created on SEPT/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="kalilinux"
SCRIPT_NAME="IbyC-$TOOL"
SHLL=$(env | grep SHELL | awk -F "/" '{print $7}')
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}

if [ $SHLL = "bin" ]
then
        CONFIG_FILE="$PREFIX/etc/bash.bashrc"
	TEXT="4a GOPATH=$HOME/go"
elif [ $SHLL = "fish" ]
then
        CONFIG_FILE="$PREFIX/etc/fish/config.fish"
	TEXT="20a set GOPATH $HOME/go"
else
        printf "$Y\n[w]$R ERROR 2 :$W Incompatible shell$W"
        ctrl_c
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
#CHECK ROOT
if [ -x /system/xbin/su ] || [ -x /su/bin/su ] || [ -x /sbin/su ]; then
        ROOT="YES"
fi
echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

#INSTALLATION
printf "$Y\n[TO-DO]─➤$W (I)nstall or (U)ninstall "
while read -p "[I/U]─➤ " IU && [ -z $IU ]; do
	printf "$Y\n[TO-DO]─➤$W (I)nstall or (U)ninstall "
done

if [ $IU = "I" ]; then
		printf "$G\n[UPGRADING]─➤$W Updating and upgrading Termux\n"
		sleep 1
		yes | pkg update && pkg install curl proot wget tar > /dev/null 2>&1
		printf "$G\n[STEP 1]─➤$W Installing Kali Linux (It could take a while)...\n"
		sleep 2
		curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Kali/kali-lxde.sh | bash
clear
		printf "Welcome to Andronix | Kali\nPlease follow the next steps\n"
		sleep 1
		printf "$G\n[STEP 2]─➤$W Start Kali Linux:$Y\n\tPress enter to run kali linux and then copy, page\n\tand run the next command into kali linux shell\n$W\napt update -y && apt install curl proot tar -y && curl https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Kali/kali-lxde.sh | bash\n\n$G\n➤$Y In the middle of process you have to set your login password\nand answer a question as$R NO\n$W"
		sleep 3
		printf "$G\n[STEP 3]─➤$W Copy, page and run the next command into kali linux shell$G\n➤$W echo \"deb http://http.kali.org/kali kali-rolling main none-free contrib\" >> /etc/apt/sources.list && apt update -y && apt upgrade -y\n"
		sleep 3
		printf "$G\n[STEP 4]─➤$W Open VNC app and add connection at$G localhost:1\n➤$W Set a session name and login with your password\n\n\t$Y Press$G enter$Y to continue$W\n"
		read enter
		if [ -e $HOME/start-kali.sh ]
		then
			./start-kali.sh
		else
			printf "$R\n[ERR-KALI]─➤ Going to https://t.me/Ivam3_Bot$W\n"
			exit
		fi
elif [ $IU = "U" ]; then
	printf "$Y\n[UNINSTALLING]─➤$W It could take a while ...\n"
	wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Uninstall/Kali/UNI-kali.sh
	bash UNI-kali.sh

else
	printf "$R\n[ERROR-OPC]─➤ Type I or U\n$W"
	exit
fi


#ENDING SCRIPT
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
#                                               @Ivam3
