#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
trap ctrl_c 2

IFS=$'\n\t'
TOOL="johntheripper"
SCRIPT_NAME="IbyC-$TOOL"
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

Install(){
JTRv="1.8.0"
JTRtar="https://download.openwall.net/pub/projects/john/contrib/android/john-$JTRv-android-1.tar.gz"

for del in $PREFIX/bin/john $PREFIX/opt/john $TMPDIR/john-$JTRv-android;do
        if [ -e $del ] || [ -d $del ];then
                rm -rf $del
        fi
done

yes|pkg update && pkg upgrade && pkg install wget
wget -q $JTRtar -O $TMPDIR/john-$JTRv-android-1.tar.gz
cd $TMPDIR;tar -xvzf john-$JTRv-android-1.tar.gz
rm -rf john-$JTRv-android-1.tar.gz
mkdir -p $PREFIX/opt/john
JTR="$PREFIX/opt/john"
mv $TMPDIR/john-$JTRv-android/user/* $JTR
ln -s $JTR/john.conf $JTR/john.ini
case $(uname -m) in
#       declare -a arch=(arm64-v8a  armeabi  armeabi-v7a  mips  mips64  x86  x86_64)
    aarch64)
        mv $TMPDIR/john-$JTRv-android/libs/arm64-v8a/* $JTR
        ;;
    arm)
        mv $TMPDIR/john-$JTRv-android/libs/armeabi/* $JTR
        ;;
    armhf)
        mv $TMPDIR/john-$JTRv-android/libs/armeabi-v7a/* $JTR
        ;;
    i686)
        mv $TMPDIR/john-$JTRv-android/libs/x86/* $JTR
        ;;
    x86_64)
        mv $TMPDIR/john-$JTRv-android/libs/x86_64/* $JTR
        ;;
esac
rm -rf $TMPDIR/john-$JTRv-android
chmod +x $JTR/*
echo "#!/data/data/com.termux/files/usr/bin/bash" > $PREFIX/bin/john
echo "#This script find and execute johntheripper tool" >> $PREFIX/bin/john
echo "#" >> $PREFIX/bin/john
echo "R='\033[1;31m'"  >> $PREFIX/bin/john
echo "W='\033[0m'" >> $PREFIX/bin/john
echo " " >> $PREFIX/bin/john
echo "if [ -d $PREFIX/opt/john ];then" >> $PREFIX/bin/john
echo "        cd $PREFIX/opt/john" >> $PREFIX/bin/john
echo "        ./john" >> $PREFIX/bin/john
echo "else" >> $PREFIX/bin/john
echo "        printf \"\$R[ERROR]─➤ JohnTheRipper is not installed\$W\"" >> $PREFIX/bin/john
echo "fi" >> $PREFIX/bin/john
echo "#            @Ivam3" >> $PREFIX/bin/john
chmod +x $PREFIX/bin/john
}

printf "$G[+]─➤$W Looking for $SCRIPT_NAME..";
sleep 2
        printf "$G. DONE!!$W\n"
        sleep 1
printf "$G[+]─➤$W Installing $TOOL..";
	sleep 1
	Install
        printf "$G. DONE!!$W"
        sleep 1

#ENDING SCRIPT
if [ -d $JTR ]; then
	printf "$G\n[DIR TOOL]─➤$W $JTR"
	printf "$G\n[RUN IT]─➤$W john\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n      [FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
