#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
trap ctrl_c 2

IFS=$'\n\t'
TOOL="shc"
SCRIPT_NAME="IbyC-$TOOL"
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-➤ You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-➤ $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

Install() {
	shcVer="3.8.9"
	for i in $DIR/shc $PREFIX/bin/shc;do
        if [ -d $i ] || [ -e $i ];then
                rm -rf $i
        fi
done
yes|pkg update && pkg upgrade && pkg install wget make
wget -q http://www.datsi.fi.upm.es/~frosal/sources/shc-$shcVer.tgz -O $TMPDIR/shc-$shcVer.tgz
if [ -e $TMPDIR/shc-$shcVer.tgz ]; then
        cd $TMPDIR
        tar -xvzf $TMPDIR/shc-$shcVer.tgz
	rm -rf $TMPDIR/shc-$shcVer.tgz
        if [ -d $TMPDIR/shc-$shcVer ]; then
                cd $TMPDIR/shc-$shcVer
                make;make install
                if [ -e $TMPDIR/shc-$shcVer/shc ]; then
                        mv $TMPDIR/shc-$shcVer/shc $PREFIX/bin/
			rm -rf $TMPDIR/shc-$shcVer
		else
			printf "$R\n[ERR-make]─➤$W Going to https://t.me/Ivam3_Bot"
			rm -rf $TMPDIR/shc-$shcVer
			exit
                fi
                wget -q https://raw.githubusercontent.com/yanncam/UnSHc/master/latest/unshc.sh -O $PREFIX/bin/unshc
                sed 's|/tmp/XXXXXX|$PREFIX/tmp/XXXXXX|g' -i $PREFIX/bin/unshc
                chmod +x $PREFIX/bin/*
        fi
else
        printf "$R\n[ERR-shc]─➤$W Going to https://t.me/Ivam3_Bot"
        exit
fi
}

printf "$G[+]─➤$W Looking for $SCRIPT_NAME..";
sleep 2
        printf "$G. DONE!!$W\n"
        sleep 1
printf "$G[+]─➤$W Installing $TOOL..";
	sleep 1
	Install
        printf "$G. DONE!!$W"
        sleep 1

#ENDING SCRIPT
if [ -e $PREFIX/bin/$SCRIPT_NAME ]; then
	printf "$G\n[DIR TOOL]─➤$W $PREFIX/bin/"
	printf "$G\n[RUN IT]─➤$W $SCRIPT_NAME -h or un$SCRIPT_NAME -h \n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n      [FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
