#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="xerosploit"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
if [ -x /system/xbin/su ]; then
        printf "true\n"
elif [ -x /su/bin/su ]; then
        printf "true\n"
elif [ -x /sbin/su ]; then
        printf "true\n"
else
        printf "false\n"
fi

echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

#INSTALLATION
TMP_PATH=$PREFIX/opt/$TOOL

if [ "$RUROOT" = "true" ]; then
        if [ -d $TMP_PATH ]; then
                rm -rf $TMP_PATH
        fi
        yes | pkg update && pkg upgrade && pkg install git nmap hping3 build-essential python python2 ruby git libpcap
        git clone https://github.com/LionSec/xerosploit.git $TMP_PATH > /dev/null 2>&1
        for i in python2 python ; do
                $i -m pip install tabulate terminaltables
        done
        chmod +x -R $TMP_PATH/tools
        pushd $TMP_PATH/tools/bettercap/
        gem build bettercap.*
        gem install xettercap-*
        rm xettercap-*
        popd
        rm $TMP_PATH/run.sh
        rm $TMP_PATH/$TOOL.py
        curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/fix-tools/$TOOL.py -o $TMP_PATH/$TOOL.py
else
        printf "$R\n[W]:-> You need to be root to get Xerosploit$W\n"
        sleep 1
        exit
fi

#ENDING SCRIPT
if [ -d $TMP_PATH ]; then
	printf "$G\n[DIR TOOL]:->$W $TMP_PATH"
	printf "$G\n[RUN IT]:->$W sudo python2 $TOOL.py\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
