#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="quack"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

if [ -L $HOME/storage/external-1 ]; then
	SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
	if [ ! -z $SDCARD ]; then
		DIR=$SDCARD
	else
		DIR=$HOME
	fi
else
	DIR=$HOME
fi
printf "$Y\n[IbyC]:->$W Set the directory where $SCRIPT_NAME will be install$Y\n[default]:->$W $DIR\n"
read -p "[R]:-> " ANSW
DIR="${ANSW:-${DIR}}"

#INSTALLATION
if [ -d $DIR/$TOOL ]; then
        rm -rf $DIR/$TOOL
fi
Basic() {
        for module in phonenumbers requests scapy wget argparse ; do
                for py in python python2 ; do
                        $py -m pip install $module
                done
        done
}
LDFLAGS() {
        export LDFLAGS="-L/system/lib/ -lm -lcompiler_rt"
        for module in phonenumbers requests scapy wget argparse⏎; do
                for py in python python2 ; do
                        $py -m pip install $module --global-option="build_ext" --global-option="--disable-jpeg"
                done
        done
}
SODIUM() {
        export SODIUM_INSTALL=system
        for module in phonenumbers requests scapy wget argparse ; do
                for py in python python2 ; do
                        $py -m pip install --no-binary :all: $module
                done
        done
}
yes | pkg update && pkg upgrade && pkg install git python python2
#git clone https://github.com/entynetproject/quack.git $DIR/$TOOL 2> /dev/null
wget https://github.com/ivam3/i-Haklab/raw/master/.set/to-install/$TOOL.zip
unzip $TOOL.zip -d $DIR
rm $TOOL.zip
mv $TOOL $DIR
chmod 711 -R $DIR/$TOOL
for file in bin install.sh uninstall.sh ; do
        if [ -e $DIR/$TOOL/$file ] || [ -d $DIR/$TOOL/$file ]; then
                rm -rf $DIR/$TOOL/$file
        fi
done

printf "$Y\n[!]->$W There are 3 methods to install the repositories : choose one$Y\n[01]->$W BASIC$Y\n[02]->$W LDFLAGS$Y\n[03]->$W SODIUM\n\n"

while read -p "[*]:-> " ANSW && [ -z $ANSW ]; do
        continue
done
if [ $ANSW = '1' ] || [ $ANSW = '01' ]; then
        Basic
elif [ $ANSW = '2' ] || [ $ANSW = '02' ]; then
        LDFLAGS
elif [ $ANSW = '3' ] || [ $ANSW = '03' ]; then
        SODIUM
else
        printf "$R[w]->$W method $ANSW doesn't exist\n"
        exit
fi

#ENDING SCRIPT
if [ -d $DIR/$TOOL ]; then
	printf "$G\n[DIR TOOL]:->$W $DIR/$TOOL"
	printf "$G\n[RUN IT]:->$W python $TOOL\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
