#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="vpn"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){ printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";exit;}

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

Install(){
	iHDB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
	yes|pkg install wget tor torsocks proxychains-ng >/dev/null 2>&1
	wget -q ${iHDB}/etc/tor/torrc -O $PREFIX/etc/tor/torrc
	wget -q ${iHDB}/etc/proxychains.conf -O $PREFIX/etc/proxychains.conf
	for i in myip mypip swip;do
		wget -q ${iHDB}/bin/$i -O $PREFIX/bin/$i
		chmod +x $PREFIX/bin/$i
	done
	}

printf "$G[+]─➤$W Looking for $SCRIPT_NAME..";
sleep 2
        printf "$G. DONE!!$W\n"
        sleep 1
printf "$G[+]─➤$W Installing $TOOL..";
        sleep 1
	Install
        printf "$G. DONE!!\n$W"
        sleep 1

#ENDING SCRIPT
if [ -e $PREFIX/bin/myip ]; then
        printf "$G\n[COMMAND myip]:->$W Show the IP assigned by proxy"
fi
if [ -e $PREFIX/bin/mypip ]; then
        printf "$G\n[COMMAND mypip]:->$W Show the IP assigned by your ISP"
fi
if [ -e $PREFIX/bin/swip ]; then
        printf "$G\n[COMMAND swip]:->$W Switch the IP assigned by proxy"
fi
if [ -e $PREFIX/bin/tor ]; then
        printf "$G\n[RUN IT]$Y\n   ╰──[session one]:─>$W Run tor$G\n         ╰──[another session]:->$W Run any command prefixing proxychains4\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
