#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="EMBED"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
#CHECK ROOT
if [ -x /system/xbin/su ] || [ -x /su/bin/su ] || [ -x /sbin/su ]; then
        ROOT="true"
fi

if [ -L $HOME/storage/external-1 ]; then
	SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
	if [ ! -z $SDCARD ]; then
		DIR=$SDCARD
	else
		DIR=$HOME
	fi
else
	DIR=$HOME
fi
printf "$Y\n[IbyC]:->$W Set the directory where $SCRIPT_NAME will be install$Y\n[default]:->$W $DIR\n"
read -p "[R]:-> " ANSW
DIR="${ANSW:-${DIR}}"

#INSTALLATION
if [ -d $DIR/$TOOL ]; then
        rm -rf $DIR/$TOOL
fi
yes|pkg update && pkg upgrade && pkg install git
git clone https://github.com/ivam3/embed.git $DIR/embed
chmod +x -R $DIR/embed
pushd $DIR/embed
bash $DIR/embed/setup

#ENDING SCRIPT
if [ -d $DIR/embed ]; then
	printf "$G\n[DIR TOOL]:->$W $DIR/embed"
	printf "$G\n[RUN IT]:->$W ruby $TOOL.rb\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
