#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="tangalanga"
SCRIPT_NAME="IbyC-$TOOL"
SHLL=$(env | grep SHELL | awk -F "/" '{print $7}')
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3_Bot$W\n"
		exit
}

if [ $SHLL = "bin" ]
then
        CONFIG_FILE="$PREFIX/etc/bash.bashrc"
        TEXT="4a GOPATH=$HOME/go"
elif [ $SHLL = "fish" ]
then
        CONFIG_FILE="$PREFIX/etc/fish/config.fish"
        TEXT="20a set GOPATH $HOME/go"
else
        printf "$Y\n[w]$R ERROR 2 :$W Incompatible shell$W"
        ctrl_c
fi

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"

DIR=$HOME/go/src/github.com

printf "$Y\n[IbyC]:->$W Set the directory where $SCRIPT_NAME will be install$Y\n[default]:->$W $DIR\n"
read -p "[R]:-> " ANSW
DIR="${ANSW:-${DIR}}"

#INSTALLATION
yes | pkg update && pkg upgrade && pkg install golang
if [ -d $DIR/$TOOL ]
then
        rm -rf $DIR/$TOOL

elif [ ! -d $DIR/ ]; then
        mkdir -p $DIR
fi
VAR=$(cat $CONFIG_FILE | grep "GOPATH")
if [ -z $VAR ]; then
        sed -i "$TEXT" $CONFIG_FILE
fi
chmod +x -R $HOME/go/
git clone github.com/elcuervo/tangalanga.git $DIR/$TOOL > /dev/null
if [ -d $DIR/$TOOL ]
then
        chmod 711 -R $DIR/$TOOL
        pushd $DIR/$TOOL
else
        printf "$R\n[w]-> ERROR 1 :$Y Going to https://t.me/Ivam3_Bot$W\n"
        exit
fi
go get
go build
go install
if [ $HOME/go/bin/$TOOL ]
then
	ln -s $HOME/go/bin/$TOOL $PREFIX/bin/tangalanga
fi
popd

#ENDING SCRIPT
if [ -d $DIR/$TOOL ]; then
	printf "$G\n[DIR TOOL]:->$W $DIR/$TOOL"
	printf "$G\n[RUN IT]:->$W $TOOL\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
