#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="webhackshl"
SCRIPT_NAME="IbyC-$TOOL"

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c() {
                echo
                printf "$Y\n[!]$R Going me on$B Telegram$R t.me/Ivam3byCinderella$W\n"
		exit
}
while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
#CHECK ROOT
if [ -x /system/xbin/su ] || [ -x /su/bin/su ] || [ -x /sbin/su ]; then
	ROOT="True"
else
	printf "$R\n[W]:-> You need a permissions root to use $TOOL $W...Aborting.\n"
	exit
fi
#BANNER
echo $(clear)
        printf "$C"
        echo "                -{ IbyC } "
        echo "   -{ SO > Android - Only for Termux } "
        echo "              -{ Coded by } "
        printf "$G"
        echo "      =============================="
        echo "      .___.                 ______,"
        echo "      |   |__ ______   ___  \_____ \ "
        echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        echo "      |   |\   / __ \| Y Y \ /      \ "
        echo "      |___| \_/ (____|__|_| /______ /"
        echo "                     \/    \/      \/ "
        echo "      ====== By ___ Cinderella ======"
        echo
printf "$C"
        echo "          [---] Join me on [---]"
        printf "$C[-]$W www.youtube.com/c/Ivam3byCinderella$C [-]\n"
        printf "      [-]$W t.me/Ivam3byCinderella$C [-]\n"
        printf "          [-]$W t.me/Ivam3_Bot$C [-]\n"
        sleep 1
printf "$C\n"
        echo "        [---] SPECIAL THANKS [---]"
        echo "                    TO "
        echo "       [-] MY MASTER CINDERELLA [-]"
printf "$W"
        echo "             People don't die"
        echo "    If they still live in the hearts"
        echo "           of their loved ones"
        echo "       We love her ... We miss her"
        echo "                  *RIP*"
printf "$R\n"
        echo "          [---] DISCLAIMER [---]"
printf "$W"
        echo "   If the law is violated with it's use"
        echo "     This would be the responsibility"
        echo "        of the user who handled it"
printf "$R"
        echo "       [-] Use At Your Own Risk [-]"
printf "\n$C         Press$G ENTER$C to continue"
        read enter
printf "$W\n"
#CREATING LOG FILE
if [ -e $PREFIX/tmp/webhackshl.log ]; then
	echo " " > $PREFIX/tmp/webhackshl.log
else
	touch  $PREFIX/tmp/webhackshl.log
fi
LOGFILE="$PREFIX/tmp/webhackshl.log"

#DEFINING DIRECTORY TO INSTALLATION
if [ -L $HOME/storage/external-1 ]; then
	SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
	find $SDCARD -type f -name "nikto.pl" 2> /dev/null >> $LOGFILE
	find $SDCARD -type f -name "whatweb" 2> /dev/null >> $LOGFILE
	find $SDCARD -type f -name "wpscan" 2> /dev/null >> $LOGFILE
	if [ ! -z $SDCARD ]; then
		DIR=$SDCARD
	else
		DIR=$HOME
	fi
else
	DIR=$HOME
fi
printf "$Y\n[IbyC]:->$W Set the directory where $SCRIPT_NAME will be install$Y\n[default]:->$W $DIR\n"
read -p "[R]:-> " ANSW
DIR="${ANSW:-${DIR}}"

#SEARCHING FOR TOOLS/REPOSITORIES NEEDED
for path in $HOME $PREFIX ; do
	find $path -type f -name "nikto.pl" 2> /dev/null >> $LOGFILE
	find $path -type f -name "whatweb" 2> /dev/null >> $LOGFILE
	find $path -type f -name "wpscan" 2> /dev/null >> $LOGFILE
done

for framework in nikto whatweb wpscan ; do
	SEARCH=$(grep -oE $framework $LOGFILE | head -n1 )
	if [ -z $SEARCH ]; then
		printf "$R\n[IbyC]:-> $framework isn't in PATH. Install it... Aborting."
		exit 1
	fi
done
for repo in dnsenum sqlmap wpscan ; do
	command -v $repo > /dev/null 2>&1 || { echo >&2 "$R\n[IbyC]:-> $repo isn't in PATH. Install it. Aborting."; exit 1; }
done

#INSTALLATION
yes|pkg update && pkg upgrade && pkg install git curl python2 python tor ruby nmap
git clone https://github.com/sechacklabs/$TOOL.git $DIR/$TOOL
curl https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/checker.py -o $DIR/$TOOL/modules/checker.py
python -m pip install fierce
chmod 711 -R $DIR/$TOOL

if [ ! -d ~/.dnsenum ]; then
        mkdir -p ~/.dnsenum
fi
cp $PREFIX/bin/dnsenum ~/.dnsenum/dnsenum.pl

if [ ! -d ~/.nikto/program ]; then
        mkdir -p ~/.nikto/program
fi
cp $(grep nikto.pl $LOGFIE | head -n1) ~/.nikto/program

if [ ! -d ~/.whatweb ]; then
        mkdir -p ~/.whatweb
fi
cp $(grep whatweb $LOGFIE | head -n1) ~/.whatweb/
echo -e "\n#!/bin/bash\n\npython $DIR/$TOOL/$TOOL" > $PREFIX/bin/$TOOL
chmod +x $PREFIX/bin/$TOOL

#ENDING SCRIPT
if [ -d $DIR/$TOOL ]; then
	printf "$G\n[DIR TOOL]:->$W $DIR/$TOOL"
	printf "$G\n[RUN IT]:->$W $TOOL or python $TOOL\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
