#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="converter"
SCRIPT_NAME="IbyC-$TOOL"
DIR=$PREFIX/bin

R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){ printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";exit;}

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done
Install(){
	DIR="$PREFIX/bin"
	iHDB="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set"
	if [ -e $DIR/$TOOL ]; then
        	rm $DIR/$TOOL
	fi
	yes|pkg install curl dialog >/dev/null 2>&1
	curl -Ls ${iHDB}/bin/$TOOL -o $DIR/$TOOL
	chmod +x $DIR/$TOOL
}

printf "$G[+]─➤$W Looking for $SCRIPT_NAME..";
sleep 2
	printf "$G. DONE!!$W\n"
        sleep 1
printf "$G[+]─➤$W Installing $TOOL..";
        sleep 1
        Install
        printf "$G. DONE!!\n$W"
        sleep 1

#ENDING SCRIPT
if [ -e $DIR/$TOOL ]; then
	printf "$G\n[DIR TOOL]:->$W $DIR/$TOOL"
	printf "$G\n[RUN IT]:->$W $TOOL\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n[FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
