#!/data/data/com.termux/files/usr/bin/bash
#Created on Feb/2020
IFS=$'\n\t'
trap ctrl_c 2
TOOL="DoS-A-Tool"
SCRIPT_NAME="IbyC-$TOOL"
R='\033[1;31m'
G='\033[1;32m'
Goke='\033[92m'
Glig=='\e[1;32m'
Y='\033[1;33m'
B='\033[1;34m'
M='\033[1;35m'
C='\033[1;36m'
W='\033[0m'

ctrl_c(){ printf "$Y\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n";}

while [ ! $(id -u) -ne 0 ]; do
	printf "$R\n[W]:-> You need to be a common user$W\n"
	exit
done
until [ -e $HOME/$SCRIPT_NAME ]; do
	printf "$R\n[W]:-> $SCRIPT_NAME file have to be in Home directory$W\n"
	exit
done

Install(){
for Del in $PREFIX/bin/$TOOL $PREFIX/bin/Ivam3 $DIR/$TOOL; do
        if [ -e $Del ] || [ -d $Del ];then
		rm -rf $Del
	fi
done
yes|pkg update && pkg upgrade && pkg install git perl
git clone https://github.com/Ivam3/$TOOL.git $DIR/$TOOL
chmod +x $DIR/$TOOL/*
}

printf "$G[+]─➤$W Looking for $TOOL..";
sleep 2
        printf "$G. DONE!!$W\n"
        sleep 1

if [ -L $HOME/storage/external-1 ]; then
	SDCARD=$(ls -l $HOME/storage/external-1 | awk '{print $11}')
        if [ ! -z $SDCARD ]; then
                DIR=$SDCARD
        else
                DIR=$HOME
        fi
else
        DIR=$HOME
fi
printf "$Y ╰─[!]─➤$W Set the directory where $TOOL will be install$Y\n    ╰─[default]─➤$W $DIR\n"
read -p "[DIR]─➤ " ANSW
DIR="${ANSW:-${DIR}}"

printf "$G[+]─➤$W Installing tool $TOOL..";
        sleep 1
#        Install
        printf "$G. DONE!!$W"
        sleep 1

#ENDING SCRIPT
if [ -d $DIR/$TOOL ]; then
	printf "$G\n[DIR TOOL]─➤$W $DIR/$TOOL"
	printf "$G\n[RUN IT]─➤$W perl $TOOL\n"
printf "$Y\n[!]-> ::::::::::::::: DONE !! :::::::::::::::: <-[!]$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
else
	printf "$R\n      [FATAL ERROR]$W"
	ctrl_c
fi
#                                               @Ivam3
