name: Deploy Flet App to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"
          channel: stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libglib2.0-0 libnss3 libx11-6 libxcomposite1 \
            libxdamage1 libxrandr2 libxtst6 libxkbcommon0 libasound2t64

      - name: Install Build Tools
        run: |
          pip install --upgrade pip
          pip install flet==0.82.0 flet-cli==0.82.0 

      - name: Build Web App
        working-directory: docs/landpage
        run: |
          export FLET_TEMPLATE_REF=0.82.0
          flet build web --base-url / --web-renderer auto --verbose
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/landpage/build/web
          publish_branch: gh-pages
          force_orphan: true # Crea una rama limpia sin historial innecesario
